[build]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction",
  "npm ci",
  "npm run build",
  "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache",
  "chmod -R a+rw storage bootstrap/cache",
  "php artisan config:cache",
  "php artisan event:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]
